name: CI
on:
  - push
  - pull_request
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn global add lerna
        name: Install Lerna
      - run: lerna bootstrap
        name: Install dependencies
      - run: lerna run format:check
        name: Check formatting
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn global add lerna
        name: Install Lerna
      - run: lerna bootstrap
        name: Install dependencies
      - run: lerna run build
        name: Build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn global add lerna
        name: Install Lerna
      - run: lerna bootstrap
        name: Install dependencies
      - run: lerna run lint
        name: Lint
