name: Package
on:
  push:
    branches:
      - master
      - package-refactor
jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - run: yarn global add lerna
        name: Install Lerna

      - run: lerna bootstrap
        name: Install dependencies

      - run: lerna run build
        name: Compile app

      - run: cp -r packages/ui/dist packages/app/ui
        name: Copy UI into app directory

      - run: yarn package --mac --publish never
        name: Package app for macOS
        working-directory: packages/app

      - uses: actions/upload-artifact@v2
        name: Upload packaged app
        with:
          name: lux-mac
          path: |
            packages/app/build/*-mac.zip
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - run: yarn global add lerna
        name: Install Lerna

      - run: lerna bootstrap
        name: Install dependencies

      - run: lerna run build
        name: Compile app

      - run: cp -r packages/ui/dist packages/app/ui
        name: Copy UI into app directory

      - run: yarn package --linux --publish never
        name: Package app for Linux
        working-directory: packages/app

      - uses: actions/upload-artifact@v2
        name: Upload packaged app
        with:
          name: lux-linux
          path: |
            packages/app/build/*.zip
            packages/app/build/*.deb
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - run: yarn global add lerna
        name: Install Lerna

      - run: lerna bootstrap
        name: Install dependencies

      - run: lerna run build
        name: Compile app

      - run: cp -r packages/ui/dist packages/app/ui
        name: Copy UI into app directory

      - run: yarn package --windows --publish never
        name: Package app for Windows
        working-directory: packages/app

      - uses: actions/upload-artifact@v2
        name: Upload packaged app
        with:
          name: lux-windows
          path: |
            packages/app/build/*.exe
